### PR TITLE
Servlet 3.1 and other updates

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* public parent to 7
* servlet 3.1 (GA change)
* jetty 9.2.7 (GA change)
* guice to 18.0
* jackson to 2.3.5 (minor, was 2.3.3)

### CODE REVIEW

**Comment by jdillon** [comment]
feature build?

**Comment by cstamas** [comment]
http://bamboo.s/browse/OSS-SIESTAF9-1

**Comment by jdillon** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
